spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/busket_schema?characterEncoding=UTF-8&serverTimezone=UTC