spring:
  profiles:
    active: mysql
  devtools:
    restart:
      enabled: true
server:
  port: 8085
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 21600
  jwt-secret-key: 'd0!doc15415B0*4G0`'
knife4j:
  enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl